---
- name: Desplegar Nginx y WordPress
  hosts: web
  become: yes
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Crear directorio WordPress
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Descargar WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extraer WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes
        creates: /var/www/html/wordpress/index.php

    - name: Configurar permisos
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Crear wp-config.php
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configurar Nginx para WordPress
      copy:
        dest: /etc/nginx/sites-available/wordpress
        content: |
          server {
              listen 80;
              server_name www.example.org;
              root /var/www/html/wordpress;
              index index.php index.html index.htm;

              location / {
                  try_files $uri $uri/ /index.php?$args;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass 192.168.200.193:9000;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }
          }
        owner: root
        group: root
        mode: '0644'

    - name: Habilitar sitio
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link

    - name: Deshabilitar default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted

    - name: Crear archivo de prueba
      copy:
        dest: /var/www/html/wordpress/test.php
        content: |
          <?php
          echo "<h1>Web Server: " . gethostname() . "</h1>";
          echo "<p>IP: " . $_SERVER['SERVER_ADDR'] . "</p>";
          ?>
        owner: www-data
        group: www-data
        mode: '0644'
