---
- name: Instalar WordPress completo en un servidor
  hosts: 192.168.200.161
  become: yes
  
  tasks:
    # PASO 1: Actualizar sistema
    - name: Actualizar paquetes
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
    
    # PASO 2: Instalar MariaDB (base de datos)
    - name: Instalar MariaDB
      apt:
        name: mariadb-server
        state: present
    
    - name: Configurar MariaDB
      shell: |
        mysql -u root <<'SQL'
        CREATE DATABASE IF NOT EXISTS wordpress;
        CREATE USER IF NOT EXISTS 'wordpress_user'@'localhost' IDENTIFIED BY 'wordpress_pass';
        GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress_user'@'localhost';
        FLUSH PRIVILEGES;
        SQL
      args:
        executable: /bin/bash
    
    # PASO 3: Instalar PHP y extensiones
    - name: Instalar PHP
      apt:
        name:
          - php-fpm
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-zip
        state: present
    
    # PASO 4: Instalar Nginx
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
    
    # PASO 5: Descargar WordPress
    - name: Descargar WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
    
    - name: Extraer WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes
        creates: /var/www/html/wordpress
    
    # PASO 6: Configurar permisos
    - name: Configurar permisos
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
    
    # PASO 7: Crear wp-config.php
    - name: Crear configuración WordPress
      copy:
        dest: /var/www/html/wordpress/wp-config.php
        content: |
          <?php
          define('DB_NAME', 'wordpress');
          define('DB_USER', 'wordpress_user');
          define('DB_PASSWORD', 'wordpress_pass');
          define('DB_HOST', 'localhost');
          define('DB_CHARSET', 'utf8mb4');
          define('DB_COLLATE', '');
          
          $table_prefix = 'wp_';
          
          define('WP_DEBUG', false);
          
          if (!defined('ABSPATH')) {
              define('ABSPATH', __DIR__ . '/');
          }
          
          require_once ABSPATH . 'wp-settings.php';
          ?>
        owner: www-data
        group: www-data
        mode: '0644'
    
    # PASO 8: Configurar Nginx
    - name: Configurar sitio Nginx
      copy:
        dest: /etc/nginx/sites-available/wordpress
        content: |
          server {
              listen 80;
              server_name _;
              
              root /var/www/html/wordpress;
              index index.php index.html index.htm;
              
              location / {
                  try_files $uri $uri/ /index.php?$args;
              }
              
              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/var/run/php/php-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }
              
              location ~ /\.ht {
                  deny all;
              }
          }
        owner: root
        group: root
        mode: '0644'
    
    - name: Habilitar sitio
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/default
        state: link
    
    - name: Eliminar default viejo
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      ignore_errors: yes
    
    # PASO 9: Reiniciar servicios
    - name: Reiniciar servicios
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - mariadb
        - php-fpm
        - nginx
    
    # PASO 10: Crear archivo de prueba
    - name: Crear página de prueba
      copy:
        dest: /var/www/html/wordpress/test.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>✅ WordPress Listo</title>
              <style>
                  body { font-family: Arial; text-align: center; margin-top: 50px; }
                  .success { color: green; font-size: 24px; }
                  .info { color: blue; }
              </style>
          </head>
          <body>
              <div class="success">✅ ¡WordPress instalado correctamente!</div>
              <div class="info">IP: {{ ansible_default_ipv4.address }}</div>
              <div class="info">Hostname: {{ ansible_hostname }}</div>
              <p><a href="/wp-admin/install.php">Instalar WordPress</a></p>
              <p><a href="/test.php">PHP Info</a></p>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'
    
    - name: Crear test PHP
      copy:
        dest: /var/www/html/wordpress/test.php
        content: |
          <?php
          echo "<h1>✅ PHP funciona correctamente</h1>";
          echo "<p>Servidor: " . gethostname() . "</p>";
          echo "<p>PHP Version: " . phpversion() . "</p>";
          
          // Probar MySQL
          $link = @mysqli_connect('localhost', 'wordpress_user', 'wordpress_pass', 'wordpress');
          if ($link) {
              echo "<p style='color:green;'>✅ MySQL: CONECTADO</p>";
              mysqli_close($link);
          } else {
              echo "<p style='color:red;'>❌ MySQL: ERROR - " . mysqli_connect_error() . "</p>";
          }
          ?>
        owner: www-data
        group: www-data
        mode: '0644'
    
    # PASO 11: Mostrar información final
    - name: Mostrar URLs de acceso
      debug:
        msg: |
          🎉 INSTALACIÓN COMPLETADA 🎉
          
          🌐 Acceso a WordPress:
          URL: http://{{ ansible_default_ipv4.address }}/
          Test PHP: http://{{ ansible_default_ipv4.address }}/test.php
          Instalar WP: http://{{ ansible_default_ipv4.address }}/wp-admin/install.php
          
          🔧 Credenciales MySQL:
          Base de datos: wordpress
          Usuario: wordpress_user
          Contraseña: wordpress_pass
          Host: localhost
          
          ⚠️  Si ves error 403:
          1. sudo chown -R www-data:www-data /var/www/html/wordpress
          2. sudo systemctl restart nginx php-fpm
